{{- with .Values.httproute }}
{{- if .gatewayName -}}
{{- $fullName := include "mychart.fullname" $ -}}
{{- $svcPort := $.Values.service.port -}}
{{- if .hostRoutes }}
{{- range .hostRoutes }}
{{- $exactPaths := $.Values.httproute.exactPaths }}
{{- if hasKey . "exactPaths" }}
{{- $exactPaths = .exactPaths }}
{{- end }}
{{- $pathPrefixes := $.Values.httproute.pathPrefixes }}
{{- if hasKey . "pathPrefixes" }}
{{- $pathPrefixes = .pathPrefixes }}
{{- end }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}-{{ .name }}-route
  namespace: {{ $.Release.Namespace }}
spec:
  parentRefs:
    - name: {{ $.Values.httproute.gatewayName }}
      namespace: {{ $.Values.httproute.namespace | default $.Release.Namespace }}
      sectionName: {{ .httpsListenerName }}
  hostnames:
    - {{ .hostname | quote }}
  rules:
  - matches:
    {{- if $exactPaths }}
    {{- range $exactPaths }}
    - path:
        type: Exact
        value: {{ . | quote }}
    {{- end }}
    {{- end }}
    {{- if $pathPrefixes }}
    {{- range $pathPrefixes }}
    - path:
        type: PathPrefix
        value: {{ . | quote }}
    {{- end }}
    {{- else }}
    - path:
        type: PathPrefix
        value: {{ $.Values.httproute.pathPrefix | quote }}
    {{- end }}
    backendRefs:
    - name: {{ $fullName }}
      port: {{ $svcPort }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}-{{ .name }}-redirect-route
  namespace: {{ $.Release.Namespace }}
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ $.Values.httproute.gatewayName }}
      namespace: {{ $.Values.httproute.namespace | default $.Release.Namespace }}
      sectionName: {{ .httpListenerName }}
  hostnames:
    - {{ .hostname | quote }}
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            port: 443
            scheme: https
            statusCode: 301
{{- end }}
{{- else }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}-route 
  namespace: {{ $.Release.Namespace }}
spec:
  parentRefs:
    - name: {{ .gatewayName }}
      namespace: {{ .namespace | default $.Release.Namespace }}
      sectionName: {{ .httpsListenerName }}
  hostnames:
  {{- range .hostnames }}
  - {{ . | quote }}
  {{- end }}
  rules:
  - matches:
    {{- if .exactPaths }}
    {{- range .exactPaths }}
    - path:
        type: Exact
        value: {{ . | quote }}
    {{- end }}
    {{- end }}
    {{- if .pathPrefixes }}
    {{- range .pathPrefixes }}
    - path:
        type: PathPrefix
        value: {{ . | quote }}
    {{- end }}
    {{- else }}
    - path:
        type: PathPrefix
        value: {{ .pathPrefix | quote }}
    {{- end }}
    backendRefs:
    - name: {{ $fullName }} # Assumes a service named 'my-service-service' is defined in the chart
      port: {{ $svcPort }}
{{- end }}

{{- if and .gatewayName (not .hostRoutes) }}
---
{{- $fullName := include "mychart.fullname" $ -}} 
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}-redirect-route
  namespace: {{ $.Release.Namespace }}
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ .gatewayName }}
      namespace: {{ .namespace | default $.Release.Namespace }}
      sectionName: {{ .httpListenerName }}
  hostnames:
  {{- range .hostnames }}
  - {{ . | quote }}
  {{- end }}
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            port: 443
            scheme: https
            statusCode: 301 # Use 301 for permanent redirect, 308 for method-preserving permanent redirect
{{- end }}
{{- end }}
{{- end }}
